FROM tensorflow/tensorflow:latest

RUN apt-get update && apt-get install -y python3-pip
ADD requirements.txt /my_server/requirements.txt
RUN pip3 install -r /my_server/requirements.txt

ADD api_tf_pred.py /my_server/server.py

WORKDIR /my_server/

CMD ["uvicorn", "server:app", "--reload", "--host", "0.0.0.0", "--port", "8088"]