kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: npd-space
  name: configmap-editor
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "update", "patch"]